name:  League Loader Request
description: Request support for a non-supported fantasy site
title: "[LEAGUE LOADER]: "
labels:
  - enhancement
assignees:
  - joeyagreco

body:
- type: input
  attributes:
    label: Fantasy Site Name
    description: The name of the fantasy site you would like added.
  validations:
    required: true

- type: input
  attributes:
    label: Fantasy Site URL
    description: The URL of the fantasy site you would like added.
  validations:
    required: true

- type: textarea
  attributes:
    label: Notes
    description: Add any additional relevant info.
  validations:
    required: false

