name:  League Loader Issue
description: Report an issue for an existing League Loader
title: "[LEAGUE LOADER]: "
labels:
  - bug
assignees:
  - joeyagreco

body:
- type: dropdown
  attributes:
    label: League Loader
    options:
     - ESPN
     - Sleeper
     - Yahoo
  validations:
    required: true

- type: textarea
  attributes:
    label: Summary
    description: Describe the new feature/improvement briefly below.
  validations:
    required: true
