name:  ✨ test
description: testeroni

body:

- type: dropdown
  attributes:
  label: League Loader
  options:
  - ESPN
  - Sleeper
    validations:
    required: true

- type: textarea
  attributes:
  label: Summary
  description: Describe the issue briefly below.
  validations:
  required: true